import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CardListService {

  constructor() { }

  movieService(){
    return [
      {
        "adult": false,
        "backdrop_path": "/5hNcsnMkwU2LknLoru73c76el3z.jpg",
        "genre_ids": 
          35,
        "id": 19404,
        "original_language": "hi",
        "original_title": "दिलवाले दुल्हनिया ले जायेंगे",
        "overview": "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
        "popularity": 25.094,
        "poster_path": "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
        "release_date": "1995-10-20",
        "title": "Dilwale Dulhania Le Jayenge",
        "video": false,
        "vote_average": 8.7,
        "vote_count": 3296
      },
      {
        "adult": false,
        "backdrop_path": "/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg",
        "genre_ids": 18,
        "id": 278,
        "original_language": "en",
        "original_title": "The Shawshank Redemption",
        "overview": "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        "popularity": 58.556,
        "poster_path": "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        "release_date": "1994-09-23",
        "title": "The Shawshank Redemption",
        "video": false,
        "vote_average": 8.7,
        "vote_count": 20349
      },
      {
        "adult": false,
        "backdrop_path": "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
        "genre_ids": 18,
        "id": 238,
        "original_language": "en",
        "original_title": "The Godfather",
        "overview": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
        "popularity": 60.801,
        "poster_path": "/eEslKSwcqmiNS6va24Pbxf2UKmJ.jpg",
        "release_date": "1972-03-14",
        "title": "The Godfather",
        "video": false,
        "vote_average": 8.7,
        "vote_count": 15213
      },
      {
        "adult": false,
        "backdrop_path": "/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
        "genre_ids": 
          10749,
        "id": 724089,
        "original_language": "en",
        "original_title": "Gabriel's Inferno Part II",
        "overview": "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
        "popularity": 29.693,
        "poster_path": "/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
        "release_date": "2020-07-31",
        "title": "Gabriel's Inferno Part II",
        "video": false,
        "vote_average": 8.6,
        "vote_count": 1358
      },
      {
        "adult": false,
        "backdrop_path": "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
        "genre_ids":36,
        "id": 424,
        "original_language": "en",
        "original_title": "Schindler's List",
        "overview": "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
        "popularity": 33.497,
        "poster_path": "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
        "release_date": "1993-11-30",
        "title": "Schindler's List",
        "video": false,
        "vote_average": 8.6,
        "vote_count": 12148
      },
      {
        "adult": false,
        "backdrop_path": "/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
        "genre_ids":10749,
        "id": 696374,
        "original_language": "en",
        "original_title": "Gabriel's Inferno",
        "overview": "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
        "popularity": 15.207,
        "poster_path": "/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
        "release_date": "2020-05-29",
        "title": "Gabriel's Inferno",
        "video": false,
        "vote_average": 8.6,
        "vote_count": 2172
      },
      {
        "adult": false,
        "backdrop_path": "/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
        "genre_ids": 35,
        "id": 761053,
        "original_language": "en",
        "original_title": "Gabriel's Inferno Part III",
        "overview": "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
        "popularity": 23.975,
        "poster_path": "/qtX2Fg9MTmrbgN1UUvGoCsImTM8.jpg",
        "release_date": "2020-11-19",
        "title": "Gabriel's Inferno Part III",
        "video": false,
        "vote_average": 8.6,
        "vote_count": 921
      },
      {
        "adult": false,
        "backdrop_path": "/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg",
        "genre_ids":80,
        "id": 240,
        "original_language": "en",
        "original_title": "The Godfather: Part II",
        "overview": "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
        "popularity": 39.433,
        "poster_path": "/sSuQTCZwqKrNBNIsksO9IAUoWP9.jpg",
        "release_date": "1974-12-20",
        "title": "The Godfather: Part II",
        "video": false,
        "vote_average": 8.6,
        "vote_count": 9161
      },
      {
        "adult": false,
        "backdrop_path": "/1EAxNqdkVnp48a7NUuNBHGflowM.jpg",
        "genre_ids": 16,
        "id": 283566,
        "original_language": "ja",
        "original_title": "シン・エヴァンゲリオン劇場版:||",
        "overview": "In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.",
        "popularity": 153.193,
        "poster_path": "/g7xEBLb5hOTPpjQxIMrCNWbnjna.jpg",
        "release_date": "2021-03-08",
        "title": "Evangelion: 3.0+1.0 Thrice Upon a Time",
        "video": false,
        "vote_average": 8.6,
        "vote_count": 404
      },
      {
        "adult": false,
        "backdrop_path": "/l5K9elugftlcyIHHm4nylvsn26X.jpg",
        "genre_ids": 18,
        "id": 255709,
        "original_language": "ko",
        "original_title": "소원",
        "overview": "After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.",
        "popularity": 8.078,
        "poster_path": "/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg",
        "release_date": "2013-10-02",
        "title": "Hope",
        "video": false,
        "vote_average": 8.6,
        "vote_count": 237
      },
      {
        "adult": false,
        "backdrop_path": "/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg",
        "genre_ids": 10749,
        "id": 372058,
        "original_language": "ja",
        "original_title": "君の名は。",
        "overview": "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
        "popularity": 147.591,
        "poster_path": "/q719jXXEzOoYaps6babgKnONONX.jpg",
        "release_date": "2016-08-26",
        "title": "Your Name.",
        "video": false,
        "vote_average": 8.6,
        "vote_count": 8156
      },
      {
        "adult": false,
        "backdrop_path": "/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
        "genre_ids":16,
        "id": 129,
        "original_language": "ja",
        "original_title": "千と千尋の神隠し",
        "overview": "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
        "popularity": 65.576,
        "poster_path": "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
        "release_date": "2001-07-20",
        "title": "Spirited Away",
        "video": false,
        "vote_average": 8.5,
        "vote_count": 12174
      },
      {
        "adult": false,
        "backdrop_path": "/u1wHUA0R48FH4WV3sGqjwx3aNZm.jpg",
        "genre_ids":16,
        "id": 632632,
        "original_language": "ja",
        "original_title": "映画 ギヴン",
        "overview": "The film centers on the love relationship among the band's bassist Haruki Nakayama, drummer Akihiko Kaji, and Akihiko's roommate and ex-boyfriend Ugetsu Murata.",
        "popularity": 107.241,
        "poster_path": "/xKCtoYHUyX8zAg68eemnYa2orep.jpg",
        "release_date": "2020-08-22",
        "title": "Given",
        "video": false,
        "vote_average": 8.5,
        "vote_count": 277
      },
      {
        "adult": false,
        "backdrop_path": "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
        "genre_ids": 35,
        "id": 496243,
        "original_language": "ko",
        "original_title": "기생충",
        "overview": "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
        "popularity": 71.173,
        "poster_path": "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        "release_date": "2019-05-30",
        "title": "Parasite",
        "video": false,
        "vote_average": 8.5,
        "vote_count": 12715
      },
      {
        "adult": false,
        "backdrop_path": "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
        "genre_ids":28,
        "id": 634649,
        "original_language": "en",
        "original_title": "Spider-Man: No Way Home",
        "overview": "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        "popularity": 12971.91,
        "poster_path": "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        "release_date": "2021-12-15",
        "title": "Spider-Man: No Way Home",
        "video": false,
        "vote_average": 8.5,
        "vote_count": 2295
      },
      {
        "adult": false,
        "backdrop_path": "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
        "genre_ids": 18,
        "id": 389,
        "original_language": "en",
        "original_title": "12 Angry Men",
        "overview": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
        "popularity": 21.943,
        "poster_path": "/e02s4wmTAExkKg0yF4dEG98ZRpK.jpg",
        "release_date": "1957-04-10",
        "title": "12 Angry Men",
        "video": false,
        "vote_average": 8.5,
        "vote_count": 6037
      },
      {
        "adult": false,
        "backdrop_path": "/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg",
        "genre_ids":80,
        "id": 497,
        "original_language": "en",
        "original_title": "The Green Mile",
        "overview": "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
        "popularity": 44.254,
        "poster_path": "/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
        "release_date": "1999-12-10",
        "title": "The Green Mile",
        "video": false,
        "vote_average": 8.5,
        "vote_count": 13197
      },
      {
        "adult": false,
        "backdrop_path": "/m5HPKCi7GdhKmxPTcOQmcLfEmZ9.jpg",
        "genre_ids":14,
        "id": 532067,
        "original_language": "ja",
        "original_title": "映画 この素晴らしい世界に祝福を！紅伝説",
        "overview": "It is not strange that the Demon Lord's forces fear the Crimson Demons, the clan from which Megumin and Yunyun originate. Even if the Demon Lord's generals attack their village, the Crimson Demons can just easily brush them off with their supreme mastery of advanced and overpowered magic.  When Yunyun receives a seemingly serious letter regarding a potential disaster coming to her hometown, she immediately informs Kazuma Satou and the rest of his party. After a series of wacky misunderstandings, it turns out to be a mere prank by her fellow demon who wants to be an author. Even so, Megumin becomes worried about her family and sets out toward the Crimson Demons' village with the gang.  There, Kazuma and the others decide to sightsee the wonders of Megumin's birthplace. However, they soon come to realize that the nonsense threat they received might have been more than just a joke.",
        "popularity": 174.812,
        "poster_path": "/j73LuQcA21KvkVFcroWWMN8tTJv.jpg",
        "release_date": "2019-08-30",
        "title": "KonoSuba:God's Blessing on this Wonderful World!",
        "video": false,
        "vote_average": 8.5,
        "vote_count": 329
      },
      {
        "adult": false,
        "backdrop_path": "/yHtB4KHNigx3ZoxDvQbW2SOXGfq.jpg",
        "genre_ids":10751,
        "id": 441130,
        "original_language": "en",
        "original_title": "Wolfwalkers",
        "overview": "In a time of superstition and magic, when wolves are seen as demonic and nature an evil to be tamed, a young apprentice hunter comes to Ireland with her father to wipe out the last pack. But when she saves a wild native girl, their friendship leads her to discover the world of the Wolfwalkers and transform her into the very thing her father is tasked to destroy.",
        "popularity": 18.885,
        "poster_path": "/ehAKuE48okTuonq6TpsNQj8vFTC.jpg",
        "release_date": "2020-10-26",
        "title": "Wolfwalkers",
        "video": false,
        "vote_average": 8.5,
        "vote_count": 645
      },
      {
        "adult": false,
        "backdrop_path": "/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
        "genre_ids":53,
        "id": 155,
        "original_language": "en",
        "original_title": "The Dark Knight",
        "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
        "popularity": 65.893,
        "poster_path": "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        "release_date": "2008-07-14",
        "title": "The Dark Knight",
        "video": false,
        "vote_average": 8.5,
        "vote_count": 26430
      }
    ]
  }
}
